[tool.poetry]
name = "api_boilerplate"
version = "1.0"
description = "A dockerized and production ready python API template with no setup required."
authors = ["Adishwar Rishi <adiswa123@gmail.com>"]
license = "LGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.2"
Flask = "^2.2.2"
mypy-extensions = "^0.4.3"
uWSGI = "^2.0.20"
SQLAlchemy = "^1.4.41"
PyMySQL = "^1.0.2"
cryptography = "^38.0.1"
bcrypt = "^4.0.0"
pavlova = "^0.1.3"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.3"
mypy = "^0.981"
alembic = "^1.8.1"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
poetryup = "^0.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
